# Generate dev/COVERAGE.md from the crosswalk.
#
# The page shown to coauthors: every routine the book names, what it is called
# in xucinet 2.0, and how far along it is. Re-run at the end of each chapter:
#   source("dev/make-coverage.R")
# from the package root, with the package loadable (devtools::load_all() or an
# installed copy).
#
# Status is worked out here rather than stored, for the same reason xhelp()
# works it out at call time: a status written into a file starts lying the day
# the next routine lands.

pkg <- "xucinet"
if (!requireNamespace(pkg, quietly = TRUE)) {
  stop("load the package first: devtools::load_all()", call. = FALSE)
}
ns <- asNamespace(pkg)

tbl <- utils::read.csv("inst/extdata/crosswalk-routines.csv",
                       stringsAsFactors = FALSE, colClasses = "character")

# The golden family each chapter's fixtures live in. A chapter with no family
# yet has none, and its routines cannot be further along than "coded".
family_of <- c("5" = "transform", "6" = "multivariate", "9" = "centrality",
               "10" = "cohesion")

# Two chapter 10 routines are checked against the Phase 0 density family
# rather than their own chapter's, because the Density form and
# Network | Whole-Network Measures share an engine and that run saved the
# whole block. A per-chapter family cannot express that, so they say so here.
family_of_fn <- c(xdensity = "density", xcohesion = "density")

# A family counts as generated once it holds at least one ##h fixture.
family_has_goldens <- function(family) {
  if (is.na(family)) return(FALSE)
  d <- file.path("inst", "goldens", family)
  if (!dir.exists(d)) return(FALSE)
  length(list.files(d, pattern = "\\.##[hH]$")) > 0
}
families <- unique(c(family_of, family_of_fn))
generated <- vapply(families, family_has_goldens, logical(1))
names(generated) <- families

# Routines that will not be written, and why. Kept here rather than in the
# crosswalk because the crosswalk is the book's, and this is our decision.
dropped <- c(
  xcreateproject   = "design question 5.11: xucinet 2.0 has no project object",
  xaddtoproject    = "design question 5.11: xucinet 2.0 has no project object",
  xremovefromproject = "design question 5.11: xucinet 2.0 has no project object",
  xreachbetweenness = "no UCINET equivalent; withdrawn 7 Sep 2026"
)

# The first bare lowercase name in the 2.0 column, the way xhelp() reads it.
first_name <- function(x) {
  hits <- regmatches(x, gregexpr("\\b[a-z_][a-z0-9_.]*\\b", x))[[1]]
  hits <- setdiff(hits, c("none", "print", "save", "data", "or", "and", "the"))
  if (length(hits)) hits[1] else NA_character_
}

status_of <- function(fn, chapter) {
  if (is.na(fn) || !nzchar(fn)) return("not started")
  if (fn %in% names(dropped)) return("dropped")
  if (is.null(get0(fn, envir = ns, mode = "function"))) return("not started")
  # [[ ]] on a named vector errors for a name that is not there, and most
  # chapters have no golden family yet. A per-function override wins.
  fam <- if (fn %in% names(family_of_fn)) family_of_fn[[fn]]
         else if (chapter %in% names(family_of)) family_of[[chapter]]
         else NA_character_
  if (is.na(fam) || !isTRUE(generated[[fam]])) return("coded, goldens pending")
  "done"
}

tbl$fn <- vapply(tbl$name_2, first_name, character(1))
tbl$status <- vapply(seq_len(nrow(tbl)),
                     function(i) status_of(tbl$fn[i], tbl$chapter[i]),
                     character(1))

# ---- write it out -----------------------------------------------------------

esc <- function(x) gsub("|", "\\|", x, fixed = TRUE)
chapters <- unique(tbl$chapter)
chapters <- chapters[order(suppressWarnings(as.numeric(chapters)), chapters)]

counts <- table(factor(tbl$status,
                       levels = c("done", "coded, goldens pending",
                                  "not started", "dropped")))

out <- c(
  "# Coverage",
  "",
  sprintf("Generated by `dev/make-coverage.R` on %s. Do not edit by hand.",
          format(Sys.Date(), "%d %B %Y")),
  "",
  "Every routine the book names, from `inst/extdata/crosswalk-routines.csv`,",
  "against the xucinet 2.0 function that serves it.",
  "",
  "| status | meaning | count |",
  "|---|---|---|",
  sprintf("| done | written, tested, and checked against UCINET goldens | %d |",
          counts[["done"]]),
  sprintf("| coded, goldens pending | written and tested; the golden tests skip until the UCINET batch is run | %d |",
          counts[["coded, goldens pending"]]),
  sprintf("| not started | no function yet | %d |", counts[["not started"]]),
  sprintf("| dropped | will not be written; the reason is given below | %d |",
          counts[["dropped"]]),
  "")

for (ch in chapters) {
  rows <- tbl[tbl$chapter == ch, ]
  out <- c(out,
           sprintf("## Chapter %s", ch),
           "",
           "| section | topic | UCINET | 2.0 function | status |",
           "|---|---|---|---|---|",
           sprintf("| %s | %s | %s | %s | %s |",
                   esc(rows$section), esc(rows$topic), esc(rows$menu),
                   ifelse(is.na(rows$fn) | !nzchar(rows$fn), "-",
                          paste0("`", rows$fn, "()`")),
                   rows$status),
           "")
}

if (length(dropped)) {
  out <- c(out, "## Dropped", "",
           sprintf("- `%s()` - %s", names(dropped), unname(dropped)), "")
}

writeLines(out, "dev/COVERAGE.md")
cat("wrote dev/COVERAGE.md:", nrow(tbl), "rows,",
    counts[["done"]], "done,", counts[["coded, goldens pending"]], "coded,",
    counts[["not started"]], "not started,", counts[["dropped"]], "dropped\n")
