# Generate R/aliases-1e.R from the crosswalk.
#
# The list of ASNR 1e names lives in the book repo, not here, so this reads it
# rather than restating it: one source of truth, and re-running picks up any
# change to the crosswalk. Run with the working directory at the package root:
#   source("data-raw/make-aliases.R")

crosswalk <- "C:/Users/sborg2/GitHub/asnr2e/crosswalk/ASNR2e_routine_crosswalk_v1.xlsx"

# ---- what the crosswalk says ------------------------------------------------

sheet <- readxl::read_excel(crosswalk, sheet = "Routines", .name_repair = "minimal")
old_col <- "xUCINET 0.x name (ASNR 1e)"
new_col <- "Proposed xucinet 2.0 name"

# 1e names are xCamelCase; 2.0 names are lowercase (D3).
extract_old <- function(x) regmatches(x, gregexpr("\\bx[A-Z][A-Za-z0-9]*\\b", x))[[1]]
extract_new <- function(x) {
  hits <- regmatches(x, gregexpr("\\b[a-z_][a-z0-9_.]*\\b", x))[[1]]
  hits <- setdiff(hits, c("none", "data", "print", "load", "or", "and", "the"))
  if (length(hits)) hits[1] else NA_character_
}

pairs <- list()
for (i in seq_len(nrow(sheet))) {
  old <- as.character(sheet[[old_col]][i])
  new <- as.character(sheet[[new_col]][i])
  if (is.na(old)) next
  for (o in extract_old(old)) {
    if (is.null(pairs[[o]])) pairs[[o]] <- extract_new(if (is.na(new)) "" else new)
  }
}

# ---- decisions the crosswalk cannot make for itself -------------------------

# Five 1e names sit in rows whose 2.0 column names a different routine, because
# the 1e listed several functions against one topic. Resolved by what the 1e
# function actually did, not by which name happened to come first in the cell.
overrides <- c(
  xCreateProject     = "xcreateproject",   # not xread: it made a project
  xAddToProject      = "xaddtoproject",    # not xread: it added to one
  xQAPCorrelation    = "xqap",             # not xsimilarities
  xCombineNodes      = "xcombinenodes",    # not xblockmodel
  xPermuteRegression = "xregression",      # not xcorrelation
  # xRegression is a real 0.x export and belongs with the regression routine,
  # not with the correlation row it happens to be listed in.
  xRegression        = "xregression"
)

# The twelve names only the 0.x NAMESPACE exported used to be listed here. They
# are now rows in the crosswalk's Routines sheet, under chapter 0 / "(0.x only)"
# (asnr2e 45f4428), so this script reads them with everything else and the alias
# list and the crosswalk stay one document rather than two that can drift.

# Names that appear in the 0.x column but were never functions. xEigenvector is
# a method option in the 1e's core-periphery text; as an alias it would be worse
# than useless, because anyone typing it wants eigenvector centrality and would
# get a core-periphery routine (Steve, 6 Sep 2026).
drop <- c("xEigenvector")

# A few aliases need a sentence the generic message cannot give.
notes <- c(
  xNegativeDegreeCentrality = paste(
    "Negative-tie degree is xdegree() on the negative-tie matrix, e.g.",
    "xdegree(net, relation = \"negative\"). For the negative-tie centrality the",
    "3e discusses, see xpncentrality()."),
  xNegativeWeightedCentrality = paste(
    "Negative-tie degree is xdegree() on the negative-tie matrix, e.g.",
    "xdegree(net, relation = \"negative\"). For the negative-tie centrality the",
    "3e discusses, see xpncentrality().")
)

map <- unlist(pairs)
map[names(overrides)] <- overrides

map <- map[!is.na(map) & nzchar(map)]
map <- map[setdiff(names(map), drop)]
map <- map[order(tolower(names(map)))]

cat("aliases:", length(map), " distinct targets:", length(unique(map)), "\n")
# Informational only, and guarded: this script has to be runnable when the
# package cannot be loaded, which is exactly the case after it writes a file
# that does not parse.
live <- tryCatch(
  vapply(map, function(f) exists(f, envir = asNamespace("xucinet")), logical(1)),
  error = function(e) rep(NA, length(map)))
if (!anyNA(live)) {
  cat("targets that exist today:", sum(live), "| still to be written:", sum(!live), "\n")
}

# ---- write the file ---------------------------------------------------------

# encodeString rather than paste0('"', x, '"'): the notes contain quoted R code,
# and unescaped inner quotes would generate a file that does not parse.
q <- function(x) encodeString(x, quote = '"')
body <- vapply(names(map), function(old) {
  sprintf("#' @rdname xucinet-1e\n#' @export\n%s <- function(...) alias_1e(%s, %s, ...)",
          old, q(old), q(map[[old]]))
}, character(1))

header <- c(
'# ASNR 1e function names, as deprecated wrappers.',
'#',
'# Generated by data-raw/make-aliases.R from the crosswalk in the book repo.',
'# Do not edit by hand: re-run the generator instead, so the list stays tied to',
'# the crosswalk rather than drifting from it.',
'#',
'# Every 1e name resolves, including the ones the 1e spelled inconsistently',
'# (xWalkTrap and xWalktrap, xLabelProp and xLabelPropagation, and the rest).',
'# Most 2.0 targets belong to Phase 1 or later and do not exist yet; those',
'# wrappers stop with a message naming the routine they are waiting for, and',
'# start working the day it lands.',
'',
"#' ASNR 1e function names",
"#'",
"#' The function names used in *Analyzing Social Networks with R* (1st edition)",
"#' and the xUCINET 0.x package, kept so that code written against the first",
"#' edition still runs. Each is a thin wrapper that names its 2.0 replacement",
"#' and calls it.",
"#'",
"#' These are not the package's interface and are not documented in the",
"#' vignettes. New code should use the 2.0 names; `xucinet_1e_names()` lists",
"#' every alias and what it maps to.",
"#'",
"#' @param ... Passed unchanged to the 2.0 function.",
"#' @return Whatever the 2.0 function returns.",
"#' @name xucinet-1e",
"#' @keywords internal",
'NULL',
'',
'# alias -> 2.0 name. Exposed through xucinet_1e_names() so the test suite can',
'# walk the whole list rather than a sample of it.',
sprintf('xucinet_1e_map <- c(\n%s\n)',
        paste(sprintf('  %s = %s', names(map), q(unname(map))), collapse = ",\n")),
'',
'# Extra guidance for aliases whose replacement is not a simple rename.',
sprintf('xucinet_1e_notes <- c(\n%s\n)',
        paste(sprintf('  %s = %s', names(notes), q(unname(notes))), collapse = ",\n")),
'',
"#' The 1e alias table",
"#'",
"#' @return A named character vector: 1e name to 2.0 name.",
"#' @keywords internal",
"#' @export",
'xucinet_1e_names <- function() xucinet_1e_map',
'',
'# One wrapper body for all of them. A target that does not exist yet is not an',
'# error in the alias layer, it is a routine not written yet, and the message',
'# says which one so the reader knows what to wait for.',
'alias_1e <- function(old, new, ...) {',
'  # [[ ]] on a named vector errors for a name that is not there, and most',
'  # aliases have no note.',
'  note <- if (old %in% names(xucinet_1e_notes)) xucinet_1e_notes[[old]] else ""',
'  fn <- get0(new, envir = asNamespace("xucinet"), mode = "function")',
'  if (is.null(fn)) {',
'    stop(old, "() was the ASNR 1e name for what xucinet 2.0 calls ", new, "().\\n",',
'         "  ", new, "() is not written yet; it belongs to a later phase.\\n",',
'         "  This wrapper exists so the 1e name resolves, and will start working",',
'         " the day ", new, "() lands.",',
'         if (nzchar(note)) paste0("\\n  ", note) else "", call. = FALSE)',
'  }',
'  message(old, "() is the ASNR 1e name. xucinet 2.0 calls it ", new, "().",',
'          if (nzchar(note)) paste0("\\n  ", note) else "")',
'  fn(...)',
'}',
'')

writeLines(c(header, "", body), "R/aliases-1e.R")
cat("wrote R/aliases-1e.R with", length(map), "wrappers\n")
