# Generate R/aliases-1e.R from the crosswalk.
#
# The list of ASNR 1e names lives in the book repo, not here, so this reads it
# rather than restating it: one source of truth, and re-running picks up any
# change to the crosswalk. Run with the working directory at the package root:
#   source("data-raw/make-aliases.R")

crosswalk <- "C:/Users/sborg2/GitHub/asnr2e/crosswalk/ASNR2e_routine_crosswalk_v1.xlsx"

# ---- what the crosswalk says ------------------------------------------------

sheet <- readxl::read_excel(crosswalk, sheet = "Routines", .name_repair = "minimal")
old_col <- "xUCINET 0.x name (ASNR 1e)"
new_col <- "Proposed xucinet 2.0 name"

# 1e names are xCamelCase; 2.0 names are lowercase (D3).
extract_old <- function(x) regmatches(x, gregexpr("\\bx[A-Z][A-Za-z0-9]*\\b", x))[[1]]
extract_new <- function(x) {
  hits <- regmatches(x, gregexpr("\\b[a-z_][a-z0-9_.]*\\b", x))[[1]]
  hits <- setdiff(hits, c("none", "data", "print", "load", "or", "and", "the"))
  if (length(hits)) hits[1] else NA_character_
}

pairs <- list()
for (i in seq_len(nrow(sheet))) {
  old <- as.character(sheet[[old_col]][i])
  new <- as.character(sheet[[new_col]][i])
  if (is.na(old)) next
  for (o in extract_old(old)) {
    if (is.null(pairs[[o]])) pairs[[o]] <- extract_new(if (is.na(new)) "" else new)
  }
}

# ---- decisions the crosswalk cannot make for itself -------------------------

# Five 1e names sit in rows whose 2.0 column names a different routine, because
# the 1e listed several functions against one topic. Resolved by what the 1e
# function actually did, not by which name happened to come first in the cell.
overrides <- c(
  xCreateProject     = "xcreateproject",   # not xread: it made a project
  xAddToProject      = "xaddtoproject",    # not xread: it added to one
  xQAPCorrelation    = "xqap",             # not xsimilarities
  xCombineNodes      = "xcombinenodes",    # not xblockmodel
  xPermuteRegression = "xregression",      # not xcorrelation
  # xRegression is a real 0.x export and belongs with the regression routine,
  # not with the correlation row it happens to be listed in.
  xRegression        = "xregression"
)

# Twelve names the released 0.x NAMESPACE exports that the crosswalk does not
# list. Included so that 1e code resolves whether or not the book mentioned the
# function. Targets follow the crosswalk's naming for the same routine.
extras <- c(
  xAddAttributesToProject   = "xaddtoproject",
  xAttributeToNetwork       = "xattributetomatrix",
  xBlockmodel               = "xblockmodel",
  xBlockmodelOptimizing     = "xblockoptimize",
  xCombineTies              = "xcombine",
  xCorePeriphery            = "xcoreperiphery",
  xDualStructuralEquivalence = "xstructuralequivalence",
  xMultipleTieComposition   = "xtiecomposition",
  xNegativeDegreeCentrality = "xdegree",
  xNegativeWeightedCentrality = "xdegree",
  xPermuteQAP               = "xqap",
  xRemoveFromProject        = "xremovefromproject"
)

map <- unlist(pairs)
map[names(overrides)] <- overrides
map <- c(map, extras[setdiff(names(extras), names(map))])
map <- map[!is.na(map) & nzchar(map)]
map <- map[order(tolower(names(map)))]

cat("aliases:", length(map), " distinct targets:", length(unique(map)), "\n")
live <- vapply(map, function(f) exists(f, envir = asNamespace("xucinet")), logical(1))
cat("targets that exist today:", sum(live), "| still to be written:", sum(!live), "\n")

# ---- write the file ---------------------------------------------------------

q <- function(x) paste0('"', x, '"')
body <- vapply(names(map), function(old) {
  sprintf("#' @rdname xucinet-1e\n#' @export\n%s <- function(...) alias_1e(%s, %s, ...)",
          old, q(old), q(map[[old]]))
}, character(1))

header <- c(
'# ASNR 1e function names, as deprecated wrappers.',
'#',
'# Generated by data-raw/make-aliases.R from the crosswalk in the book repo.',
'# Do not edit by hand: re-run the generator instead, so the list stays tied to',
'# the crosswalk rather than drifting from it.',
'#',
'# Every 1e name resolves, including the ones the 1e spelled inconsistently',
'# (xWalkTrap and xWalktrap, xLabelProp and xLabelPropagation, and the rest).',
'# Most 2.0 targets belong to Phase 1 or later and do not exist yet; those',
'# wrappers stop with a message naming the routine they are waiting for, and',
'# start working the day it lands.',
'',
"#' ASNR 1e function names",
"#'",
"#' The function names used in *Analyzing Social Networks with R* (1st edition)",
"#' and the xUCINET 0.x package, kept so that code written against the first",
"#' edition still runs. Each is a thin wrapper that names its 2.0 replacement",
"#' and calls it.",
"#'",
"#' These are not the package's interface and are not documented in the",
"#' vignettes. New code should use the 2.0 names; `xucinet_1e_names()` lists",
"#' every alias and what it maps to.",
"#'",
"#' @param ... Passed unchanged to the 2.0 function.",
"#' @return Whatever the 2.0 function returns.",
"#' @name xucinet-1e",
"#' @keywords internal",
'NULL',
'',
'# alias -> 2.0 name. Exposed through xucinet_1e_names() so the test suite can',
'# walk the whole list rather than a sample of it.',
sprintf('xucinet_1e_map <- c(\n%s\n)',
        paste(sprintf('  %s = %s', names(map), q(unname(map))), collapse = ",\n")),
'',
"#' The 1e alias table",
"#'",
"#' @return A named character vector: 1e name to 2.0 name.",
"#' @keywords internal",
"#' @export",
'xucinet_1e_names <- function() xucinet_1e_map',
'',
'# One wrapper body for all of them. A target that does not exist yet is not an',
'# error in the alias layer, it is a routine not written yet, and the message',
'# says which one so the reader knows what to wait for.',
'alias_1e <- function(old, new, ...) {',
'  fn <- get0(new, envir = asNamespace("xucinet"), mode = "function")',
'  if (is.null(fn)) {',
'    stop(old, "() was the ASNR 1e name for what xucinet 2.0 calls ", new, "().\\n",',
'         "  ", new, "() is not written yet; it belongs to a later phase.\\n",',
'         "  This wrapper exists so the 1e name resolves, and will start working",',
'         " the day ", new, "() lands.", call. = FALSE)',
'  }',
'  message(old, "() is the ASNR 1e name. xucinet 2.0 calls it ", new, "().")',
'  fn(...)',
'}',
'')

writeLines(c(header, "", body), "R/aliases-1e.R")
cat("wrote R/aliases-1e.R with", length(map), "wrappers\n")
