# xdensity against UCINET's own numbers, at 1e-6.
#
# Fixtures generated by running inst/goldens/density/make_goldens.txt in UCINET
# on 4 Sep 2026, with the session log saved beside them. UCINET's density()
# returns a Density and an AvgDeg column, one row per relation; cohesion()
# returns 33 whole-network measures as rows, one column per relation.
#
# Every test skips rather than fails if its fixture is missing, so the suite
# still runs on a checkout that has not regenerated them.

tol <- 1e-6

test_that("the harness finds the goldens whatever case UCINET wrote them in", {
  expect_true(nzchar(goldens_dir("density")))
  expect_true(file.exists(file.path(goldens_dir("density"), "make_goldens.txt")))
  for (f in c("campnet", "hightech", "davis", "baker_journals")) {
    expect_true(file.exists(file.path(goldens_dir("density"), paste0(f, ".##h"))),
                info = f)
  }
  # asked for in lower case, written by UCINET in upper case
  expect_true(golden_exists("g_campnet_den"))
})

test_that("parse_golden_log picks numbers out of a UCINET log block", {
  f <- tempfile(); on.exit(unlink(f))
  writeLines(c("DENSITY", "", "Density          0.17647059",
               "Avg Degree       3.00000000", "No. of Ties     54",
               "some prose that is not a measure"), f)
  got <- parse_golden_log(f)
  expect_equal(unname(got[["Density"]]), 0.17647059)
  expect_equal(unname(got[["Avg Degree"]]), 3)
  expect_equal(unname(got[["No. of Ties"]]), 54)
  expect_false("some prose that is not a measure" %in% names(got))
})

# ---- campnet: binary, directed ----------------------------------------------

test_that("campnet density and average degree match UCINET", {
  skip_if_no_golden("g_campnet_den")
  gold <- golden_matrix("g_campnet_den")
  res <- xdensity(campnet)
  expect_equal(res$summary$Density, unname(gold[1, "Density"]), tolerance = tol)
  expect_equal(res$summary$`Avg Degree`, unname(gold[1, "AvgDeg"]), tolerance = tol)
})

test_that("the campnet whole-network block matches UCINET", {
  skip_if_no_golden("g_campnet_coh")
  gold <- golden_matrix("g_campnet_coh")
  res <- xdensity(campnet)
  expect_equal(res$summary$Density, unname(gold["Density", 1]), tolerance = tol)
  expect_equal(res$summary$`Avg Degree`, unname(gold["Avg Degree", 1]), tolerance = tol)
  expect_equal(res$summary$`No. of Ties`, unname(gold["# of ties", 1]), tolerance = tol)
  expect_equal(nrow(as.matrix(campnet)), unname(gold["# of nodes", 1]))
})

# ---- hightech: three relations ----------------------------------------------

test_that("every hightech relation matches UCINET, in stack order", {
  skip_if_no_golden("g_hightech_den")
  gold <- golden_matrix("g_hightech_den")
  expect_equal(nrow(gold), xnrelations(hightech))
  # UCINET labels the rows with the relation names, so this also checks we agree
  # on which relation is which rather than merely on three numbers.
  expect_equal(rownames(gold), xrelations(hightech))
  for (k in seq_len(nrow(gold))) {
    res <- xdensity(hightech, relation = k)
    expect_equal(res$summary$Density, unname(gold[k, "Density"]),
                 tolerance = tol, info = rownames(gold)[k])
    expect_equal(res$summary$`Avg Degree`, unname(gold[k, "AvgDeg"]),
                 tolerance = tol, info = rownames(gold)[k])
  }
})

test_that("selecting a relation by name gives the same as by position", {
  skip_if_no_golden("g_hightech_den")
  gold <- golden_matrix("g_hightech_den")
  expect_equal(xdensity(hightech, relation = "Friendship")$summary$Density,
               unname(gold["Friendship", "Density"]), tolerance = tol)
})

# ---- davis: 2-mode ----------------------------------------------------------

test_that("2-mode density counts every cell, as UCINET does", {
  # The case that caught a real bug: we were excluding a pseudo-diagonal from an
  # 18 x 14 matrix, where cell (i,i) is woman i at event i and means nothing.
  # That gave 0.324 against UCINET's 0.353.
  skip_if_no_golden("g_davis_den")
  gold <- golden_matrix("g_davis_den")
  res <- xdensity(davis)
  expect_equal(res$summary$Density, unname(gold[1, "Density"]), tolerance = tol)
  expect_equal(res$summary$Density, sum(as.matrix(davis)) / (18 * 14), tolerance = tol)
})

test_that("2-mode average degree uses the column count, as UCINET does", {
  # Only 2-mode data tells the denominators apart: davis is 18 women by 14
  # events and UCINET reports 89/14, not 89/18.
  skip_if_no_golden("g_davis_den")
  gold <- golden_matrix("g_davis_den")
  expect_equal(xdensity(davis)$summary$`Avg Degree`,
               unname(gold[1, "AvgDeg"]), tolerance = tol)
  expect_equal(xdensity(davis)$summary$`Avg Degree`, 89 / 14, tolerance = tol)
})

# ---- baker_journals: valued -------------------------------------------------

test_that("density of valued data is the mean cell value, as UCINET has it", {
  skip_if_no_golden("g_baker_den")
  gold <- golden_matrix("g_baker_den")
  res <- xdensity(baker_journals)
  expect_equal(res$summary$Density, unname(gold[1, "Density"]), tolerance = tol)
  expect_equal(res$summary$`Avg Degree`, unname(gold[1, "AvgDeg"]), tolerance = tol)
  expect_gt(res$summary$Density, 1)   # a mean, not a proportion
})

test_that("dichotomising valued data matches UCINET's own dichotomisation", {
  skip_if_no_golden("g_baker_bin_den")
  gold <- golden_matrix("g_baker_bin_den")
  expect_equal(xdensity(baker_journals, weighted = FALSE)$summary$Density,
               unname(gold[1, "Density"]), tolerance = tol)
})

test_that("we count the same ties UCINET does, off the diagonal", {
  skip_if_no_golden("g_baker_bin")
  ours <- (as.matrix(baker_journals) > 0) * 1
  gold <- golden_matrix("g_baker_bin")
  off <- row(ours) != col(ours)
  expect_equal(unname(ours[off]), unname(gold[off]), tolerance = tol)
  # UCINET's dichot() zeroes the diagonal; ours keeps whatever was there. It
  # makes no difference to density, which excludes the diagonal either way, but
  # it is a real difference in the transform and belongs in the ledger.
  expect_true(all(diag(gold) == 0))
  expect_true(all(diag(ours) == 1))   # baker's diagonal is non-zero throughout
})

test_that("the valued and dichotomised densities really do differ", {
  skip_if_no_golden("g_baker_den")
  skip_if_no_golden("g_baker_bin_den")
  expect_false(isTRUE(all.equal(
    unname(golden_matrix("g_baker_den")[1, "Density"]),
    unname(golden_matrix("g_baker_bin_den")[1, "Density"]))))
})

# ---- the printed report against UCINET's log --------------------------------

test_that("the log records the run that produced these fixtures", {
  log <- file.path(goldens_dir("density"), "log_make_goldens.txt")
  skip_if_not(file.exists(log), "session log not captured")
  txt <- readLines(log, warn = FALSE)
  expect_true(any(grepl("run make_goldens.txt", txt, fixed = TRUE)))
  expect_true(any(grepl("treated as 2-mode because it is not square", txt)))
})

test_that("our density agrees with the number printed in UCINET's log", {
  log <- file.path(goldens_dir("density"), "log_make_goldens.txt")
  skip_if_not(file.exists(log), "session log not captured")
  txt <- readLines(log, warn = FALSE)
  # the CAMPNET row of the first Density block: label then Density then AvgDeg
  row <- grep("CAMPNET\\s+0\\.", txt, value = TRUE)[1]
  skip_if(is.na(row), "no CAMPNET density row in the log")
  nums <- as.numeric(regmatches(row, gregexpr("[0-9]+\\.[0-9]+", row))[[1]])
  expect_equal(xdensity(campnet)$summary$Density, nums[1], tolerance = tol)
  expect_equal(xdensity(campnet)$summary$`Avg Degree`, nums[2], tolerance = tol)
})
