# ASNR 1e function names, as deprecated wrappers.
#
# Generated by data-raw/make-aliases.R from the crosswalk in the book repo.
# Do not edit by hand: re-run the generator instead, so the list stays tied to
# the crosswalk rather than drifting from it.
#
# Every 1e name resolves, including the ones the 1e spelled inconsistently
# (xWalkTrap and xWalktrap, xLabelProp and xLabelPropagation, and the rest).
# Most 2.0 targets belong to Phase 1 or later and do not exist yet; those
# wrappers stop with a message naming the routine they are waiting for, and
# start working the day it lands.

#' ASNR 1e function names
#'
#' The function names used in *Analyzing Social Networks with R* (1st edition)
#' and the xUCINET 0.x package, kept so that code written against the first
#' edition still runs. Each is a thin wrapper that names its 2.0 replacement
#' and calls it.
#'
#' These are not the package's interface and are not documented in the
#' vignettes. New code should use the 2.0 names; `xucinet_1e_names()` lists
#' every alias and what it maps to.
#'
#' @param ... Passed unchanged to the 2.0 function.
#' @return Whatever the 2.0 function returns.
#' @name xucinet-1e
#' @keywords internal
NULL

# alias -> 2.0 name. Exposed through xucinet_1e_names() so the test suite can
# walk the whole list rather than a sample of it.
xucinet_1e_map <- c(
  xAddAttributesToProject = "xaddtoproject",
  xAddToProject = "xaddtoproject",
  xAlterCompositionCat = "xaltercomposition",
  xAlterCompositionCon = "xaltercomposition",
  xAttributeToMatrix = "xattributetomatrix",
  xAttributeToNetwork = "xattributetomatrix",
  xAutoRegression = "xautoregression",
  xAutoregression = "xautoregression",
  xAverageDistance = "xcohesion",
  xBetaCentrality = "xbeta",
  xBetaReachCentrality = "xbetareach",
  xBetweennessCentrality = "xbetweenness",
  xBiCliques = "xbicliques",
  xBiComembership = "xbicliques",
  xBlockmodel = "xblockmodel",
  xBlockmodelOptimizing = "xblockoptimize",
  xBlockOptimization = "xblockoptimize",
  xBlockOptimize = "xblockoptimize",
  xBreadth = "xcohesion",
  xCentralization = "xcentralization",
  xCliqueComembership = "xcliques",
  xCliqueOverlap = "xcliques",
  xCliques = "xcliques",
  xCliquesCoMembership = "xcliques",
  xCliquesMembership = "xcliques",
  xCliquesOverlap = "xcliques",
  xClosenessCentrality = "xcloseness",
  xCombineNodes = "xcombinenodes",
  xCombineTies = "xcombine",
  xCompactness = "xcohesion",
  xComponents = "xcomponents",
  xConcentration = "xcoreperiphery",
  xConnectedness = "xcomponents",
  xContinuousCorePeriphery = "xcoreperiphery",
  xConvertData = "as_igraph",
  xCorePeriphery = "xcoreperiphery",
  xCorrelation = "xcorrelation",
  xCorrespondenceAnalysis = "xcorrespondence",
  xCreateProject = "xcreateproject",
  xCyclicality = "xtransitivity",
  xDegreeCentrality = "xdegree",
  xDensity = "xdensity",
  xDichotomize = "xdichotomize",
  xDiscreteCorePeriphery = "xcoreperiphery",
  xDisplayBlocked = "xblockmodel",
  xDualCorePeriphery = "xcoreperiphery",
  xDualDiscreteCorePeriphery = "xcoreperiphery",
  xDualLouvainMethod = "xlouvain",
  xDualStructuralEquivalence = "xsimilarities",
  xEgoAlterSimilarityCat = "xegoaltersimilarity",
  xEgoAlterSimilarityCon = "xegoaltersimilarity",
  xEgonetStructure = "xegonet",
  xEigenvectorCentrality = "xeigenvector",
  xFastGreedy = "xfastgreedy",
  xFragmentation = "xcomponents",
  xGeodesicDistance = "xgeodesic",
  xGirvanNewman = "xgirvannewman",
  xGroupHomophily = "xdensitybygroups",
  xGroupsCohesion = "xdensitybygroups",
  xHierarchicalCluster = "xhclust",
  xHierarchicalClustering = "xhclust",
  xImputeMissingData = "ximpute",
  xInducedCentrality = "xinduced",
  xLabelProp = "xlabelpropagation",
  xLabelPropagation = "xlabelpropagation",
  xLouvainMethod = "xlouvain",
  xLRQAP = "xlrqap",
  xMDS = "xmds",
  xMRQAP = "xmrqap",
  xMultipleTieComposition = "xtiecomposition",
  xNegativeDegreeCentrality = "xdegree",
  xNegativeWeightedCentrality = "xpncentrality",
  xNormalize = "xnormalize",
  xPermuteCor = "xcorrelation",
  xPermuteCorrelation = "xcorrelation",
  xPermuteQAP = "xqap",
  xPermuteRegression = "xregression",
  xPNCentrality = "xpncentrality",
  xProfileSimilarity = "xstructuralequivalence",
  xProportionReach = "xcohesion",
  xQAPCorrelation = "xqap",
  xQAPLogisticRegression = "xlrqap",
  xQAPRegression = "xmrqap",
  xReachCentrality = "xreach",
  xReciprocity = "xreciprocity",
  xREGE = "xrege",
  xRegression = "xregression",
  xRemoveFromProject = "xremovefromproject",
  xStructuralEquivalence = "xstructuralequivalence",
  xStructuralHoles = "xstructuralholes",
  xSymmetrize = "xsymmetrize",
  xTieCombine = "xcombine",
  xTieComposition = "xtiecomposition",
  xTieDichotomize = "xdichotomize",
  xTieNormalization = "xnormalize",
  xTieSymmetrize = "xsymmetrize",
  xTieTranspose = "xtranspose",
  xTransitivity = "xtransitivity",
  xTranspose = "xtranspose",
  xTwoModeToBipartite = "xbipartite",
  xTwoModeToOneMode = "xaffiliations",
  xTwomodeToOnemode = "xaffiliations",
  xValuedTieComposition = "xvaluedtiecomposition",
  xWalkTrap = "xwalktrap",
  xWalktrap = "xwalktrap"
)

# Extra guidance for aliases whose replacement is not a simple rename.
xucinet_1e_notes <- c(
  xDualCorePeriphery = "2-mode core/periphery waits on a decision about UCINET's genetic algorithm versus the dual projection the book describes (dev/STATUS.md, open questions); xcoreperiphery() takes 1-mode data.",
  xDualDiscreteCorePeriphery = "2-mode core/periphery waits on a decision about UCINET's genetic algorithm versus the dual projection the book describes (dev/STATUS.md, open questions); xcoreperiphery() takes 1-mode data.",
  xDualStructuralEquivalence = "For 2-mode data, compare rows or columns with xsimilarities(net, mode = \"rows\") or mode = \"cols\".",
  xBiCliques = "Two-mode cliques (bicliques) belong to chapter 13 and are written with it; xcliques() takes 1-mode data.",
  xBiComembership = "Two-mode cliques (bicliques) belong to chapter 13 and are written with it; xcliques() takes 1-mode data.",
  xDualLouvainMethod = "On 2-mode data xlouvain() waits on a decision between UCINET's bipartite modularity and the dual projection the book describes (GitHub issue #18).",
  xMDS = "type =\"similarities\" or \"dissimilarities\" is now required; the 1e default is gone because a 0/1 matrix cannot tell the two apart. See ?xmds.",
  xHierarchicalClustering = "type = \"similarities\" or \"dissimilarities\" is now required; the 1e default is gone because a 0/1 matrix cannot tell the two apart. See ?xhclust.",
  xHierarchicalCluster = "type = \"similarities\" or \"dissimilarities\" is now required; the 1e default is gone because a 0/1 matrix cannot tell the two apart. See ?xhclust."
)

# Arguments an alias fixes, because its 1e name picked one variant of a 2.0
# function that now does both. The caller's own value wins.
xucinet_1e_args <- list(
  xAlterCompositionCat = list(type = "categorical"),
  xAlterCompositionCon = list(type = "continuous"),
  xEgoAlterSimilarityCat = list(type = "categorical"),
  xEgoAlterSimilarityCon = list(type = "continuous"),
  xContinuousCorePeriphery = list(type = "continuous"),
  xConcentration = list(type = "continuous"),
  xDiscreteCorePeriphery = list(type = "categorical")
)

# Aliases whose 2.0 target is not coming. These stop with the explanation
# below rather than the generic "not written yet" message, which would be a
# lie: nothing is going to land.
xucinet_1e_withdrawn <- c(
  xCreateProject = "xucinet 2.0 has no project object. A UCINET project was a folder of datasets; here you read each dataset with xread() and keep them in whatever R structure suits, a list most often. See ?xread and ?xmatch.",
  xAddToProject = "xucinet 2.0 has no project object. Read the dataset with xread() and keep it beside the others; xmatch() lines several up on one node set and xjoin() stacks them into one multi-relation dataset.",
  xAddAttributesToProject = "xucinet 2.0 has no project object. Attributes live in their own data frame; xmatch(net, attributes, attach = TRUE) puts them on the network.",
  xWalkTrap = "Walktrap is not in xucinet 2.0: the book's chapter on subgroups uses Louvain, fast greedy, Girvan-Newman, label propagation and factions instead. xlouvain(), or xcommunities() for all five side by side, is the nearest replacement; igraph::cluster_walktrap() still computes Walktrap itself.",
  xWalktrap = "Walktrap is not in xucinet 2.0: the book's chapter on subgroups uses Louvain, fast greedy, Girvan-Newman, label propagation and factions instead. xlouvain(), or xcommunities() for all five side by side, is the nearest replacement; igraph::cluster_walktrap() still computes Walktrap itself.",
  xNegativeDegreeCentrality = "Negative-tie degree is degree on the negative-tie relation: xdegree(net, relation = \"negative\"), or xdegree() on the negative-tie matrix.",
  xRemoveFromProject = "xucinet 2.0 has no project object. Datasets are ordinary R objects, so drop one the way you would drop any other; xunpack() is what splits a multi-relation dataset into separate ones."
)

#' The 1e alias table
#'
#' @return A named character vector: 1e name to 2.0 name.
#' @keywords internal
#' @export
xucinet_1e_names <- function() xucinet_1e_map

# One wrapper body for all of them. A target that does not exist yet is not an
# error in the alias layer, it is a routine not written yet, and the message
# says which one so the reader knows what to wait for.
alias_1e <- function(old, new, ...) {
  # [[ ]] on a named vector errors for a name that is not there, and most
  # aliases have no note.
  note <- if (old %in% names(xucinet_1e_notes)) xucinet_1e_notes[[old]] else ""
  if (old %in% names(xucinet_1e_withdrawn)) {
    stop(old, "() was an ASNR 1e name, and xucinet 2.0 has no replacement ",
         "for it.\n  ", xucinet_1e_withdrawn[[old]], call. = FALSE)
  }
  fn <- get0(new, envir = asNamespace("xucinet"), mode = "function")
  if (is.null(fn)) {
    stop(old, "() was the ASNR 1e name for what xucinet 2.0 calls ", new, "().\n",
         "  ", new, "() is not written yet; it belongs to a later phase.\n",
         "  This wrapper exists so the 1e name resolves, and will start working",
         " the day ", new, "() lands.",
         if (nzchar(note)) paste0("\n  ", note) else "", call. = FALSE)
  }
  message(old, "() is the ASNR 1e name. xucinet 2.0 calls it ", new, "().",
          if (nzchar(note)) paste0("\n  ", note) else "")
  # Built as a call and evaluated here, so that `...` is forwarded unevaluated
  # and the 2.0 function still sees the caller's expression for its title.
  fixed <- xucinet_1e_args[[old]]
  if (!is.null(fixed)) {
    fixed <- fixed[setdiff(names(fixed), ...names())]
    return(eval(as.call(c(list(fn, quote(...)), fixed))))
  }
  fn(...)
}


#' @rdname xucinet-1e
#' @export
xAddAttributesToProject <- function(...) alias_1e("xAddAttributesToProject", "xaddtoproject", ...)
#' @rdname xucinet-1e
#' @export
xAddToProject <- function(...) alias_1e("xAddToProject", "xaddtoproject", ...)
#' @rdname xucinet-1e
#' @export
xAlterCompositionCat <- function(...) alias_1e("xAlterCompositionCat", "xaltercomposition", ...)
#' @rdname xucinet-1e
#' @export
xAlterCompositionCon <- function(...) alias_1e("xAlterCompositionCon", "xaltercomposition", ...)
#' @rdname xucinet-1e
#' @export
xAttributeToMatrix <- function(...) alias_1e("xAttributeToMatrix", "xattributetomatrix", ...)
#' @rdname xucinet-1e
#' @export
xAttributeToNetwork <- function(...) alias_1e("xAttributeToNetwork", "xattributetomatrix", ...)
#' @rdname xucinet-1e
#' @export
xAutoRegression <- function(...) alias_1e("xAutoRegression", "xautoregression", ...)
#' @rdname xucinet-1e
#' @export
xAutoregression <- function(...) alias_1e("xAutoregression", "xautoregression", ...)
#' @rdname xucinet-1e
#' @export
xAverageDistance <- function(...) alias_1e("xAverageDistance", "xcohesion", ...)
#' @rdname xucinet-1e
#' @export
xBetaCentrality <- function(...) alias_1e("xBetaCentrality", "xbeta", ...)
#' @rdname xucinet-1e
#' @export
xBetaReachCentrality <- function(...) alias_1e("xBetaReachCentrality", "xbetareach", ...)
#' @rdname xucinet-1e
#' @export
xBetweennessCentrality <- function(...) alias_1e("xBetweennessCentrality", "xbetweenness", ...)
#' @rdname xucinet-1e
#' @export
xBiCliques <- function(...) alias_1e("xBiCliques", "xbicliques", ...)
#' @rdname xucinet-1e
#' @export
xBiComembership <- function(...) alias_1e("xBiComembership", "xbicliques", ...)
#' @rdname xucinet-1e
#' @export
xBlockmodel <- function(...) alias_1e("xBlockmodel", "xblockmodel", ...)
#' @rdname xucinet-1e
#' @export
xBlockmodelOptimizing <- function(...) alias_1e("xBlockmodelOptimizing", "xblockoptimize", ...)
#' @rdname xucinet-1e
#' @export
xBlockOptimization <- function(...) alias_1e("xBlockOptimization", "xblockoptimize", ...)
#' @rdname xucinet-1e
#' @export
xBlockOptimize <- function(...) alias_1e("xBlockOptimize", "xblockoptimize", ...)
#' @rdname xucinet-1e
#' @export
xBreadth <- function(...) alias_1e("xBreadth", "xcohesion", ...)
#' @rdname xucinet-1e
#' @export
xCentralization <- function(...) alias_1e("xCentralization", "xcentralization", ...)
#' @rdname xucinet-1e
#' @export
xCliqueComembership <- function(...) alias_1e("xCliqueComembership", "xcliques", ...)
#' @rdname xucinet-1e
#' @export
xCliqueOverlap <- function(...) alias_1e("xCliqueOverlap", "xcliques", ...)
#' @rdname xucinet-1e
#' @export
xCliques <- function(...) alias_1e("xCliques", "xcliques", ...)
#' @rdname xucinet-1e
#' @export
xCliquesCoMembership <- function(...) alias_1e("xCliquesCoMembership", "xcliques", ...)
#' @rdname xucinet-1e
#' @export
xCliquesMembership <- function(...) alias_1e("xCliquesMembership", "xcliques", ...)
#' @rdname xucinet-1e
#' @export
xCliquesOverlap <- function(...) alias_1e("xCliquesOverlap", "xcliques", ...)
#' @rdname xucinet-1e
#' @export
xClosenessCentrality <- function(...) alias_1e("xClosenessCentrality", "xcloseness", ...)
#' @rdname xucinet-1e
#' @export
xCombineNodes <- function(...) alias_1e("xCombineNodes", "xcombinenodes", ...)
#' @rdname xucinet-1e
#' @export
xCombineTies <- function(...) alias_1e("xCombineTies", "xcombine", ...)
#' @rdname xucinet-1e
#' @export
xCompactness <- function(...) alias_1e("xCompactness", "xcohesion", ...)
#' @rdname xucinet-1e
#' @export
xComponents <- function(...) alias_1e("xComponents", "xcomponents", ...)
#' @rdname xucinet-1e
#' @export
xConcentration <- function(...) alias_1e("xConcentration", "xcoreperiphery", ...)
#' @rdname xucinet-1e
#' @export
xConnectedness <- function(...) alias_1e("xConnectedness", "xcomponents", ...)
#' @rdname xucinet-1e
#' @export
xContinuousCorePeriphery <- function(...) alias_1e("xContinuousCorePeriphery", "xcoreperiphery", ...)
#' @rdname xucinet-1e
#' @export
xConvertData <- function(...) alias_1e("xConvertData", "as_igraph", ...)
#' @rdname xucinet-1e
#' @export
xCorePeriphery <- function(...) alias_1e("xCorePeriphery", "xcoreperiphery", ...)
#' @rdname xucinet-1e
#' @export
xCorrelation <- function(...) alias_1e("xCorrelation", "xcorrelation", ...)
#' @rdname xucinet-1e
#' @export
xCorrespondenceAnalysis <- function(...) alias_1e("xCorrespondenceAnalysis", "xcorrespondence", ...)
#' @rdname xucinet-1e
#' @export
xCreateProject <- function(...) alias_1e("xCreateProject", "xcreateproject", ...)
#' @rdname xucinet-1e
#' @export
xCyclicality <- function(...) alias_1e("xCyclicality", "xtransitivity", ...)
#' @rdname xucinet-1e
#' @export
xDegreeCentrality <- function(...) alias_1e("xDegreeCentrality", "xdegree", ...)
#' @rdname xucinet-1e
#' @export
xDensity <- function(...) alias_1e("xDensity", "xdensity", ...)
#' @rdname xucinet-1e
#' @export
xDichotomize <- function(...) alias_1e("xDichotomize", "xdichotomize", ...)
#' @rdname xucinet-1e
#' @export
xDiscreteCorePeriphery <- function(...) alias_1e("xDiscreteCorePeriphery", "xcoreperiphery", ...)
#' @rdname xucinet-1e
#' @export
xDisplayBlocked <- function(...) alias_1e("xDisplayBlocked", "xblockmodel", ...)
#' @rdname xucinet-1e
#' @export
xDualCorePeriphery <- function(...) alias_1e("xDualCorePeriphery", "xcoreperiphery", ...)
#' @rdname xucinet-1e
#' @export
xDualDiscreteCorePeriphery <- function(...) alias_1e("xDualDiscreteCorePeriphery", "xcoreperiphery", ...)
#' @rdname xucinet-1e
#' @export
xDualLouvainMethod <- function(...) alias_1e("xDualLouvainMethod", "xlouvain", ...)
#' @rdname xucinet-1e
#' @export
xDualStructuralEquivalence <- function(...) alias_1e("xDualStructuralEquivalence", "xsimilarities", ...)
#' @rdname xucinet-1e
#' @export
xEgoAlterSimilarityCat <- function(...) alias_1e("xEgoAlterSimilarityCat", "xegoaltersimilarity", ...)
#' @rdname xucinet-1e
#' @export
xEgoAlterSimilarityCon <- function(...) alias_1e("xEgoAlterSimilarityCon", "xegoaltersimilarity", ...)
#' @rdname xucinet-1e
#' @export
xEgonetStructure <- function(...) alias_1e("xEgonetStructure", "xegonet", ...)
#' @rdname xucinet-1e
#' @export
xEigenvectorCentrality <- function(...) alias_1e("xEigenvectorCentrality", "xeigenvector", ...)
#' @rdname xucinet-1e
#' @export
xFastGreedy <- function(...) alias_1e("xFastGreedy", "xfastgreedy", ...)
#' @rdname xucinet-1e
#' @export
xFragmentation <- function(...) alias_1e("xFragmentation", "xcomponents", ...)
#' @rdname xucinet-1e
#' @export
xGeodesicDistance <- function(...) alias_1e("xGeodesicDistance", "xgeodesic", ...)
#' @rdname xucinet-1e
#' @export
xGirvanNewman <- function(...) alias_1e("xGirvanNewman", "xgirvannewman", ...)
#' @rdname xucinet-1e
#' @export
xGroupHomophily <- function(...) alias_1e("xGroupHomophily", "xdensitybygroups", ...)
#' @rdname xucinet-1e
#' @export
xGroupsCohesion <- function(...) alias_1e("xGroupsCohesion", "xdensitybygroups", ...)
#' @rdname xucinet-1e
#' @export
xHierarchicalCluster <- function(...) alias_1e("xHierarchicalCluster", "xhclust", ...)
#' @rdname xucinet-1e
#' @export
xHierarchicalClustering <- function(...) alias_1e("xHierarchicalClustering", "xhclust", ...)
#' @rdname xucinet-1e
#' @export
xImputeMissingData <- function(...) alias_1e("xImputeMissingData", "ximpute", ...)
#' @rdname xucinet-1e
#' @export
xInducedCentrality <- function(...) alias_1e("xInducedCentrality", "xinduced", ...)
#' @rdname xucinet-1e
#' @export
xLabelProp <- function(...) alias_1e("xLabelProp", "xlabelpropagation", ...)
#' @rdname xucinet-1e
#' @export
xLabelPropagation <- function(...) alias_1e("xLabelPropagation", "xlabelpropagation", ...)
#' @rdname xucinet-1e
#' @export
xLouvainMethod <- function(...) alias_1e("xLouvainMethod", "xlouvain", ...)
#' @rdname xucinet-1e
#' @export
xLRQAP <- function(...) alias_1e("xLRQAP", "xlrqap", ...)
#' @rdname xucinet-1e
#' @export
xMDS <- function(...) alias_1e("xMDS", "xmds", ...)
#' @rdname xucinet-1e
#' @export
xMRQAP <- function(...) alias_1e("xMRQAP", "xmrqap", ...)
#' @rdname xucinet-1e
#' @export
xMultipleTieComposition <- function(...) alias_1e("xMultipleTieComposition", "xtiecomposition", ...)
#' @rdname xucinet-1e
#' @export
xNegativeDegreeCentrality <- function(...) alias_1e("xNegativeDegreeCentrality", "xdegree", ...)
#' @rdname xucinet-1e
#' @export
xNegativeWeightedCentrality <- function(net, ...) negative_weighted_1e(net, substitute(net), ...)
#' @rdname xucinet-1e
#' @export
xNormalize <- function(...) alias_1e("xNormalize", "xnormalize", ...)
#' @rdname xucinet-1e
#' @export
xPermuteCor <- function(...) alias_1e("xPermuteCor", "xcorrelation", ...)
#' @rdname xucinet-1e
#' @export
xPermuteCorrelation <- function(...) alias_1e("xPermuteCorrelation", "xcorrelation", ...)
#' @rdname xucinet-1e
#' @export
xPermuteQAP <- function(...) alias_1e("xPermuteQAP", "xqap", ...)
#' @rdname xucinet-1e
#' @export
xPermuteRegression <- function(...) alias_1e("xPermuteRegression", "xregression", ...)
#' @rdname xucinet-1e
#' @export
xPNCentrality <- function(...) alias_1e("xPNCentrality", "xpncentrality", ...)
#' @rdname xucinet-1e
#' @export
xProfileSimilarity <- function(...) alias_1e("xProfileSimilarity", "xstructuralequivalence", ...)
#' @rdname xucinet-1e
#' @export
xProportionReach <- function(...) alias_1e("xProportionReach", "xcohesion", ...)
#' @rdname xucinet-1e
#' @export
xQAPCorrelation <- function(...) alias_1e("xQAPCorrelation", "xqap", ...)
#' @rdname xucinet-1e
#' @export
xQAPLogisticRegression <- function(...) alias_1e("xQAPLogisticRegression", "xlrqap", ...)
#' @rdname xucinet-1e
#' @export
xQAPRegression <- function(...) alias_1e("xQAPRegression", "xmrqap", ...)
#' @rdname xucinet-1e
#' @export
xReachCentrality <- function(...) alias_1e("xReachCentrality", "xreach", ...)
#' @rdname xucinet-1e
#' @export
xReciprocity <- function(...) alias_1e("xReciprocity", "xreciprocity", ...)
#' @rdname xucinet-1e
#' @export
xREGE <- function(...) alias_1e("xREGE", "xrege", ...)
#' @rdname xucinet-1e
#' @export
xRegression <- function(...) alias_1e("xRegression", "xregression", ...)
#' @rdname xucinet-1e
#' @export
xRemoveFromProject <- function(...) alias_1e("xRemoveFromProject", "xremovefromproject", ...)
#' @rdname xucinet-1e
#' @export
xStructuralEquivalence <- function(...) alias_1e("xStructuralEquivalence", "xstructuralequivalence", ...)
#' @rdname xucinet-1e
#' @export
xStructuralHoles <- function(...) alias_1e("xStructuralHoles", "xstructuralholes", ...)
#' @rdname xucinet-1e
#' @export
xSymmetrize <- function(...) alias_1e("xSymmetrize", "xsymmetrize", ...)
#' @rdname xucinet-1e
#' @export
xTieCombine <- function(...) alias_1e("xTieCombine", "xcombine", ...)
#' @rdname xucinet-1e
#' @export
xTieComposition <- function(...) alias_1e("xTieComposition", "xtiecomposition", ...)
#' @rdname xucinet-1e
#' @export
xTieDichotomize <- function(...) alias_1e("xTieDichotomize", "xdichotomize", ...)
#' @rdname xucinet-1e
#' @export
xTieNormalization <- function(...) alias_1e("xTieNormalization", "xnormalize", ...)
#' @rdname xucinet-1e
#' @export
xTieSymmetrize <- function(...) alias_1e("xTieSymmetrize", "xsymmetrize", ...)
#' @rdname xucinet-1e
#' @export
xTieTranspose <- function(...) alias_1e("xTieTranspose", "xtranspose", ...)
#' @rdname xucinet-1e
#' @export
xTransitivity <- function(...) alias_1e("xTransitivity", "xtransitivity", ...)
#' @rdname xucinet-1e
#' @export
xTranspose <- function(...) alias_1e("xTranspose", "xtranspose", ...)
#' @rdname xucinet-1e
#' @export
xTwoModeToBipartite <- function(...) alias_1e("xTwoModeToBipartite", "xbipartite", ...)
#' @rdname xucinet-1e
#' @export
xTwoModeToOneMode <- function(...) alias_1e("xTwoModeToOneMode", "xaffiliations", ...)
#' @rdname xucinet-1e
#' @export
xTwomodeToOnemode <- function(...) alias_1e("xTwomodeToOnemode", "xaffiliations", ...)
#' @rdname xucinet-1e
#' @export
xValuedTieComposition <- function(...) alias_1e("xValuedTieComposition", "xvaluedtiecomposition", ...)
#' @rdname xucinet-1e
#' @export
xWalkTrap <- function(...) alias_1e("xWalkTrap", "xwalktrap", ...)
#' @rdname xucinet-1e
#' @export
xWalktrap <- function(...) alias_1e("xWalktrap", "xwalktrap", ...)
