# 1e aliases that are more than a rename. R/aliases-1e.R is generated by
# data-raw/make-aliases.R; the wrappers it writes for these names call the
# functions here, which are written by hand.

# xNegativeWeightedCentrality (0.x): PN centrality on the negated matrix
# (Steve, 23 Sep 2026, crosswalk annotation; issue #21). 0.x took the
# negative-tie matrix with positive values; xpncentrality() wants negative ties
# negative. The two agree for undirected data only: the 0.x formula used NN',
# where PN centrality, which symmetrizes, uses N^2.
negative_weighted_1e <- function(net, expr, relation = NULL) {
  message("xNegativeWeightedCentrality() is the ASNR 1e name. xucinet 2.0 runs ",
          "xpncentrality() on the negated matrix.\n  The two agree for ",
          "undirected data only: the 0.x formula used NN', where PN centrality, ",
          "which symmetrizes, uses N^2.")
  x <- xnet(net, expr)
  m <- as.matrix(x, relation = relation)
  xpncentrality(as_xucinet(-abs(m), title = x$title))
}
